@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(name = "SupplementInfo", description = "")
public class SupplementInfo {
    @Schema(description = "System channel for the transaction.", required = true)
    @JsonProperty("systemChannel")
    private String systemChannel;
    
    @Schema(description = "Channel from which the transaction originated.", required = true)
    @JsonProperty("originateChannel")
    private String originateChannel;
    
    @Schema(description = "Unique identification to identify the transaction. Format : <ChannelCode> (3) + <subId/subfunction> (3)> < YYMMDD (6)> + <running (11)> + <random (2)>")
    @JsonProperty("rquid")
    private String rquid;
    
    @Schema(description = "Branch number where the transaction originated.", required = true)
    @JsonProperty("branchNo")
    private String branchNo;
    
    @Schema(description = "ID of the employee processing the transaction.")
    @JsonProperty("employeeId")
    private String employeeId;
    
    @Schema(description = "Unit หน่วยงานเจ้าของรายการ Mandatory when employeeId = NULL")
    @JsonProperty("unit")
    private String unit;
    
    @Schema(description = "Teller number processing the transaction.")
    @JsonProperty("tellerNo")
    private String tellerNo;
    
    @Schema(description = "Authorized teller number.")
    @JsonProperty("authTellerNo")
    private String authTellerNo;
    
    @Schema(description = "Original reference number generated by originate_channel.")
    @JsonProperty("originateRef")
    private String originateRef;
    
    @Schema(description = "Source of funds for the transaction.", required = true)
    @JsonProperty("fundSof")
    private String fundSof;
    
    @Schema(description = "Reference for source of funds. (for fundSof = 4,5)")
    @JsonProperty("sofRef")
    private String sofRef;
    
    @Schema(description = "Creditor agent branch.")
    @JsonProperty("cdtrAgentBranch")
    private String cdtrAgentBranch;
    
    @Schema(description = "Customer type of the debtor (p = Person, c = Corporate).")
    @JsonProperty("dbtrCustType")
    private String dbtrCustType;
    
    @Schema(description = "Debtor telephone number.")
    @JsonProperty("dbtrTelNo")
    private String dbtrTelNo;
    
    @Schema(description = "Issuer's country code.")
    @JsonProperty("cardIssuerCountry")
    private String cardIssuerCountry;
    
    @Schema(description = "", required = true)
    @JsonProperty("feeInfo")
    private SupplementInfoFeeInfo feeInfo;
    
}
